project:
  type: website
  output-dir: docs

website:
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Sobre mí
      - href: cv.qmd
        text: CV
  page-footer: 
    left: "Copyright 2023, Santiago Vasconcello" 
    right: 
      - icon: github
        href: https://github.com/sjvasconcello
      - icon: twitter 
        href: https://twitter.com/sjvasconcello
  back-to-top-navigation: true

format:
  html:
    theme: lux
    css: styles.css
    toc: true


